---
- name: Try to access REST API using desired password
  uri:
    url: "{{ rest_api_endpoint }}"
    user: 'admin'
    password: "{{ nexus_admin_password }}"
    method: GET
    force_basic_auth: yes
    status_code: 200, 401
  register: response

  # If we get a 200, then the password has already been changed previously. The block below won't run.

- name: Still using the default password
  block:
    # I'm sort of duplicating tasks in 'call_script.yml' and 'desclare_script_each.yml' here, but those tasks
    # use 'nexus_admin_password' which obviously isn't set up. I could do some trickery with argument passing to make
    # it work, but I think this is simpler.

    - name: Declare Groovy script to change admin password
      uri:
        url: "{{ rest_api_endpoint }}"
        user: 'admin'
        password: "{{ nexus_default_admin_password }}"  # Still using the default until the completion of this block.
        body_format: json
        method: POST
        force_basic_auth: yes
        status_code: 204
        body:
          name: "password"  # The name of the script we're creating. Used in the URL below.
          type: 'groovy'
          content: "security.securitySystem.changePassword('admin', '{{ nexus_admin_password }}')"

    - name: Run Groovy script to change admin password
      uri:
        url: "{{ rest_api_endpoint }}/password/run"
        user: 'admin'
        password: "{{ nexus_default_admin_password }}"  # Still using the default until the completion of this block.
        headers:
          Content-Type: "text/plain"
        method: POST
        force_basic_auth: yes
        status_code: 200

    # The password should now be 'nexus_admin_password'. We test that fact in tests.yml.
  when: response.status == 401
