---
- name: "Removing Groovy script, if it was already declared: '{{ item }}'"
  uri:
    url: "{{ rest_api_endpoint }}/{{ item }}"
    user: 'admin'
    password: "{{ nexus_admin_password }}"
    method: DELETE
    force_basic_auth: yes
    status_code: 204,404

- name: "Declaring Groovy script: '{{ item }}'"
  uri:
    url: "{{ rest_api_endpoint }}"
    user: 'admin'
    password: "{{ nexus_admin_password }}"
    body_format: json
    method: POST
    force_basic_auth: yes
    status_code: 204
    body:
      name: "{{ item }}"
      type: 'groovy'
      content: "{{ lookup('file', 'groovy/' + item + '.groovy') }}"
