---
- include_tasks: init.yml
  tags: [ always ]

- include_tasks: nexus_install.yml
  tags: [ install ]

- include_tasks: admin_password_setup.yml
  tags: [ password ]

- include_tasks: declare_scripts.yml
  tags: [ declare ]

- include_tasks: httpd_reverse_proxy_config.yml
  when: httpd_setup_enable

- name: Deleting default repositories
  include_tasks: delete_repo_each.yml
  with_items:
    - maven-central
    - maven-public
    - maven-releases
    - maven-snapshots
    - nuget-group
    - nuget-hosted
    - nuget.org-proxy
  when: nexus_delete_default_repos

- name: Deleting default blobstore
  include_tasks: delete_blobstore_each.yml
  with_items:
    - name: default
    - name: "{{ nexus_blob_names.raw.blob }}"
    - name: "{{ nexus_blob_names.pypi.blob }}"
    - name: "{{ nexus_blob_names.docker.blob }}"
    - name: "{{ nexus_blob_names.ruby.blob }}"
    - name: "{{ nexus_blob_names.bower.blob }}"
    - name: "{{ nexus_blob_names.npm.blob }}"
    - name: "{{ nexus_blob_names.mvn.blob }}"
    - name: "{{ nexus_blob_names.gitlfs.blob }}"
  when: nexus_delete_default_blobstore

- include_tasks: setup_ldap_each.yml
  with_items: "{{ ldap_connections }}"

- include_tasks: setup_privilege_each.yml
  with_items: "{{ nexus_privileges }}"

- include_tasks: setup_role_each.yml
  with_items: "{{ nexus_roles }}"

- include_tasks: setup_user_each.yml
  with_items: "{{ nexus_local_users }}"

- name: "Digest splited blob list var"
  include_vars: blob_vars.yml
  when: nexus_blob_split

- include_tasks: create_blobstore_each.yml
  with_items: "{{ nexus_blobstores }}"

- include_tasks: create_repo_maven_proxy_each.yml
  with_items: "{{ nexus_repos_maven_proxy }}"

- include_tasks: create_repo_maven_hosted_each.yml
  with_items: "{{ nexus_repos_maven_hosted }}"

- include_tasks: create_repo_maven_group_each.yml
  with_items: "{{ nexus_repos_maven_group }}"

- block:
  - include_tasks: create_repo_docker_hosted_each.yml
    with_items: "{{ nexus_repos_docker_hosted }}"

  - include_tasks: create_repo_docker_proxy_each.yml
    with_items: "{{ nexus_repos_docker_proxy }}"

  - include_tasks: create_repo_docker_group_each.yml
    with_items: "{{ nexus_repos_docker_group }}"
  when: nexus_config_docker

- block:
  - include_tasks: create_repo_pypi_proxy_each.yml
    with_items: "{{ nexus_repos_pypi_proxy }}"

  - include_tasks: create_repo_pypi_hosted_each.yml
    with_items: "{{ nexus_repos_pypi_hosted }}"

  - include_tasks: create_repo_pypi_group_each.yml
    with_items: "{{ nexus_repos_pypi_group }}"
  when: nexus_config_pypi

- block:
  - include_tasks: create_repo_raw_proxy_each.yml
    with_items: "{{ nexus_repos_raw_proxy }}"

  - include_tasks: create_repo_raw_hosted_each.yml
    with_items: "{{ nexus_repos_raw_hosted }}"

  - include_tasks: create_repo_raw_group_each.yml
    with_items: "{{ nexus_repos_raw_group }}"
  when: nexus_config_raw

- block:
  - include_tasks: create_repo_rubygems_proxy_each.yml
    with_items: "{{ nexus_repos_rubygems_proxy }}"

  - include_tasks: create_repo_rubygems_hosted_each.yml
    with_items: "{{ nexus_repos_rubygems_hosted }}"

  - include_tasks: create_repo_rubygems_group_each.yml
    with_items: "{{ nexus_repos_rubygems_group }}"
  when: nexus_config_rubygems

- block:
  - include_tasks: create_repo_bower_proxy_each.yml
    with_items: "{{ nexus_repos_bower_proxy }}"

  - include_tasks: create_repo_bower_hosted_each.yml
    with_items: "{{ nexus_repos_bower_hosted }}"

  - include_tasks: create_repo_bower_group_each.yml
    with_items: "{{ nexus_repos_bower_group }}"
  when: nexus_config_bower

- block:
  - include_tasks: create_repo_npm_proxy_each.yml
    with_items: "{{ nexus_repos_npm_proxy }}"

  - include_tasks: create_repo_npm_hosted_each.yml
    with_items: "{{ nexus_repos_npm_hosted }}"

  - include_tasks: create_repo_npm_group_each.yml
    with_items: "{{ nexus_repos_npm_group }}"
  when: nexus_config_npm

- include_tasks: create_repo_gitlfs_hosted_each.yml
  with_items: "{{ nexus_repos_gitlfs_hosted }}"
  when: nexus_config_gitlfs

- include_tasks: call_script.yml
  vars:
    script_name: setup_anonymous_access
    args:
      anonymous_access: "{{ nexus_anonymous_access }}"

- include_tasks: call_script.yml
  vars:
    script_name: setup_base_url
    args:
      base_url: "https://{{ public_hostname }}/"

- include_tasks: call_script.yml
  vars:
    script_name: setup_email
    args:
      email_server_enabled: "{{ nexus_email_server_enabled }}"
      email_server_host: "{{ nexus_email_server_host }}"
      email_server_port: "{{ nexus_email_server_port }}"
      email_server_username: "{{ nexus_email_server_username }}"
      email_server_password: "{{ nexus_email_server_password }}"
      email_from_address: "{{ nexus_email_from_address }}"
      email_subject_prefix: "{{ nexus_email_subject_prefix }}"
      email_tls_enabled: "{{ nexus_email_tls_enabled }}"
      email_tls_required: "{{ nexus_email_tls_required }}"
      email_ssl_on_connect_enabled: "{{ nexus_email_ssl_on_connect_enabled }}"
      email_ssl_check_server_identity_enabled: "{{ nexus_email_ssl_check_server_identity_enabled }}"
      email_trust_store_enabled: "{{ nexus_email_trust_store_enabled }}"

- name: Configure branding capability
  include_tasks: call_script.yml
  vars:
    script_name: setup_capability
    args:
      capability_typeId: "rapture.branding"
      capability_properties:
        footerHtml: "{{ nexus_branding_footer }}"
        headerHtml: "{{ nexus_branding_header }}"
        footerEnabled: "{{ nexus_branding_footer != '' }}"
        headerEnabled: "{{ nexus_branding_header != '' }}"

- name: Setup scheduled tasks.
  include_tasks: call_script.yml
  vars:
    script_name: tasks
    args:
      methodName: create
      methodArgs: "{{ item }}"
  with_items: "{{ nexus_scheduled_tasks }}"
